nikita-bistaIT/BookPal

- bista_crm/__manifest__.py
- bista_crm/models/crm_lead.py
- bista_crm/security/ir.model.access.csv
- bista_crm/views/crm_lead_views.xml
- bista_purchase/__manifest__.py
- bista_purchase/models/purchase_order.py
- bista_purchase/report/purchase.xml
- bista_purchase/security/ir.model.access.csv
- bista_purchase/views/purchase_views.xml
Bista Purchase And Bista Crm
-------------------
* Created Fields In Purchase  Order And Formatted Align In Proper view
* Made Some Changes In Crm View
* Some Changes Also Made in purchase Report.
> [IMP] Made Changes In Purchase Order And Crm fields. designed UI

- bista_crm/models/crm_lead.py
Bista Crm
------------
* Added Special Pricing Type Field  On Crm View.
> Dev akshay crm

- bista_purchase/report/report_templates.xml
Bista-Purchase
---------------------
* Added Footer In Request For Quotation on Purchase Module.
> [IMP] added Footer In request For Quotation At purchase Module

- bista_sale_multi_ship/report/shipment_report_view.xml
Bista-Sale-Multi-Ship
----------------------------
* Added Subtotal in shipment report.
> [IMP] Added Subtotal value In shipment_report_view report

- bista_contact/__init__.py
- bista_contact/__manifest__.py
- bista_contact/models/res_partner.py
- bista_contact/security/ir.model.access.csv
- bista_contact/views/res_partner_views.xml
- bista_contact/wizard/__init__.py
- bista_contact/wizard/contact_status_update.py
- bista_contact/wizard/contact_status_update_views.xml
bista_contact
____________
* Added contact status update functionality in contact.
> [IMP] Added contact status update functinality in contact.

- bista_sale/report/sale.xml
- bista_sale_multi_ship/report/shipment_report_view.xml
bista_sale
___________
*  Added valid until date field in quotation/order .
_________________
* Added Valid until date field in print shipment report.
> Feature #18176

- bigcommerce_odoo_integration/views/sale_order.xml
- bista_sale_multi_ship/models/sale_multi_ship.py
bigcommerce_odoo_integration
_________________________
* made button of shipped_qty invisible
__________________
*added order by shipping_date
> Resolved Bug #18227

- bista_sale_multi_ship/__manifest__.py
- bista_sale_multi_ship/models/sale.py
- bista_sale_multi_ship/models/sale_multi_ship.py
=========================================
- Changes in delivered quantity
- Changes in available stock widget
> [ADD] Feature #18262- Compatible multishipment with kit product

- bista_purchase/models/purchase_tracking.py
- bista_purchase/views/purchase_tracking_views.xml
Added ISBN field at purchase tracking line
> [IMP] Added isbn field at purchase tracking line level

- bista_sale_multi_ship/report/shipment_report_view.xml
____________________
*Added shipping qty in multi shipment report in place of product qty.
> [IMP] Resolved bug 18227 

- bista_sale/models/sale_order.py
Bista_sale
=================================
- Hide receipts and internal transfer from sale order
> [FIX] Bug #18030- hide receipts and internal transfer from sale order

- bista_sale/models/sale_order.py
- bista_sale/views/sale_order_view.xml
Added saving amount & discounted price at sale order line and Total saving amount at sale order.
> [IMP] added saving amount and discounted price at sale order level

- bista_purchase/__manifest__.py
- bista_sales_approval/models/sale_order.py
- bista_sales_approval/views/sale_order_approval_button_view.xml
- purchase_pricelist/models/purchase_order.py
make an editable sale order line who has approver access rights and added dependency as discussed with Bhautik
> editable sale order lines on pending approval state and added dependancy

- bista_contact/models/res_partner.py
- bista_purchase/views/res_partner_views.xml
- bista_sale/models/sale_order.py
- bista_sale/views/sale_order_view.xml
Bista_Sale
===============================================
- allow to attachment in sale order line
> [ADD] Feature #18306 - allow to attachment in sale order line

- bista_contact/models/res_partner.py
- bista_contact/views/res_partner_views.xml
- bista_crm/models/crm_lead.py
- bista_crm/views/crm_lead_views.xml
- bista_purchase/models/purchase_order.py
- bista_sale/data/data.xml
- bista_sale/models/artwork_status.py
- bista_sale/models/death_type.py
- bista_sale/models/journal_customization.py
- bista_sale/models/sale_order.py
- bista_sale/views/artwork_status_view.xml
- bista_sale/views/death_type_view.xml
- bista_sale/views/journal_customization_view.xml
- bista_sale/views/sale_order_view.xml
- bista_sale_multi_ship/report/shipment_report_view.xml
Bista-Purchase, Bista-Sale, Bista-Crm, Bista- Contact, Bista-Sale-MultiShip
-----------------------------------------------------------------------------------------------------
* Feature #18280- CRM & Sales > Journal Info Tab> make Journal Customisation field multi selection possible. like we select Tags In Crm.
[done]
* Feature #18179 -Needs to check/show validation error on Add product selection[create], Save, and Confirm. like:
1. On Create Purchase order manually when a user tries to add same product warning should show that this product is already added in line, you can Update the qty there.[done]
2. On Save/Confirm Order if duplicate product lines exist then need to show the list of SKUs / Product's names in the warning with the message to add the qty in one line and remove the …
> [FIX] Confilct  Fixed.

- bista_sale_multi_ship/models/res_partner.py
=========================================
Contact Loading Issue
> [FIX] issue of loading while open contact

- bista_purchase/views/purchase_tracking_views.xml
Added form view for shipment tracking line
> [IMP] Added form view for shipment tracking line

- bista_sale/models/sale_order.py
Feature #18238: Solved wrong value on discounted price at the sale order line
> [FIX] Solved wrong value on discounted price at sale order line

- bista_sales_approval/views/sale_order_approval_button_view.xml
Make always visible customer signature tab
> [IMP] make always visible customer signature tab

- bista_customer_credit_limit_nc/models/sale.py
- bista_customer_credit_limit_nc/views/sale_view.xml
- bista_sale_multi_ship/views/sale_order_view.xml
- bista_sales_approval/models/sale_order.py
- bista_sales_approval/views/sale_order_approval_button_view.xml
- bista_sales_approval/wizard/so_reject_reason.py
Completed all changes and failed point of sales quote/order approval
> [IMP] done all changes and failed point of sales quote/order approval

- bista_stock_remarks/report/sale_report_template.xml
solved issue of sale order report
> [IMP] solved issue of sale order report

- bista_sale/models/sale_order.py
- bista_sale_multi_ship/models/sale_multi_ship.py
> [FIX] filtered the primary vendor

- bista_sale_multi_ship/models/sale.py
- bista_sale_multi_ship/models/stock.py
- bista_sales_approval/models/sale_order.py
Create different purchases based on lead time.
> [IMP] Bug #18169 - solved failed point.

- bista_purchase/models/purchase_tracking.py
Resolved issue of ship qty on purchase tracking.
> [IMP] resolved issue of ship qty on purchase tracking

- bista_customer_credit_limit_nc/views/partner_view.xml
- bista_customer_credit_limit_nc/views/sale_view.xml
- bista_sale/models/sale_order.py
- bista_sales_approval/models/sale_order.py
- bista_sales_approval/views/sale_order_approval_button_view.xml
Solved issues of sale quote/order approval.
> [FIX] Solved issues of sale quote/order approval

- bista_sale/models/sale_order.py
- bista_sale/views/sale_order_view.xml
- bista_sales_approval/data/quote_approve_email_template.xml
Feature #18560 & Feature #18566 were completed.
> Feature #18560 & Feature #18566

- bista_sales_approval/wizard/so_reject_reason.py
Feature #17869 - update rejected status
> [IMP] Feature #17869 - update rejected status

- bigcommerce_odoo_integration/models/sale_order.py
- bista_sale_multi_ship/models/res_partner.py
- bista_sale_multi_ship/views/sale_order_view.xml
solved issue when open vendor from sale order line
> [IMP] Bug #18800 - solved issue when open vendor from sale order line

- bista_sale/models/sale_order.py
- bista_sale/views/sale_order_view.xml
- bista_sales_approval/models/sale_order.py
editable discount and make readonly cover price
> [IMP] Feature #18564 - editable discount and make readonly cover price

- bista_sale/views/sale_order_view.xml
- bista_sales_approval/models/sale_order.py
> [IMP] Bug #18822 - solved issue of date order

- bigcommerce_odoo_integration/models/res_partner.py
- bigcommerce_odoo_integration/models/sale_order.py
- bigcommerce_odoo_integration/views/res_partner.xml
Updated export customer functionality from the Vraja.
> [ADD]Feature #18796 - Added customer export functionality from vraja.

- bista_purchase/views/res_partner_views.xml
Display glove type fields on contacts level kanban and form view also added searchable child field.
> [IMP] Feature #18556 - Display glove type fields on contacts level kanban and form view also added searchable child field

- bista_customer_credit_limit_nc/models/account_invoice.py
- bista_sale/views/sale_order_view.xml
- bista_sales_approval/models/sale_order.py
- sale_advance_payment/views/sale_view.xml
display stock qty widget for custom status on the sale order line
> [IMP] Bug #18863 - display stock qty widget for custom status on sale order line

- bista_sale_multi_ship/models/sale_multi_ship.py
For multi shipment display stock qty widget for custom status
> [IMP] Bug #18863 - For multi shipment display stock qty widget for custom status

- bista_purchase/models/purchase_order.py
- sale_advance_payment/models/payment.py
> [IMP] Feature #18622 - link sale order and payments

- bista_crm/models/crm_lead.py
- bista_crm/views/crm_lead_views.xml
- bista_script/script/import_vendor_pricelist.py
[IMP]Feature #18010 - Fixed the default carrier on the customer when creating a customer in lead.
> Fixed Feature #18010

- bista_purchase/data/email_template.xml
- bista_purchase/views/purchase_tracking_views.xml
- bista_purchase/views/purchase_views.xml
did changes on the purchase tracking email template and set required some field
> [IMP] Feature #18175 - did changes on purchase tracking email template and set required some field

- bista_purchase/models/purchase_order.py
- bista_sale_multi_ship/views/sale_order_view.xml
updates validation message for receipt date.
> [IMP] Bug #19019 - updates validation message

- bista_sale/views/sale_order_view.xml
- bista_sales_approval/views/sale_order_approval_button_view.xml
- sale_advance_payment/views/sale_view.xml
[IMP]Updated punch list issues like hide route, advance payment button, and payment term from the quotation.
> Updated punch list points

- bista_purchase/data/email_template.xml
- bista_purchase/models/purchase_tracking.py
open a popup for PO tracking email and modify the email template body
> [IMP] Feature #18175 - open a popup for PO tracking email and modify the email template body

- bista_purchase/models/purchase_order.py
- bista_sale/models/sale_order.py
- bista_sale/views/sale_order_view.xml
> [ADD]Added AA to PO# and order notes from SO to PO

- bista_bigcommerce_extend/models/sale_order.py
set customer reference from big commerce order ID and set validation on approving the order
> [IMP] Feature #19155 - set customer reference from big commerce order ID and set validation on approving order

- bista_purchase/__manifest__.py
- bista_purchase/data/email_template.xml
- bista_purchase/models/__init__.py
- bista_purchase/models/purchase_tracking.py
- bista_purchase/views/product_views.xml
- bista_purchase/views/purchase_tracking_views.xml
- bista_purchase/views/stock_picking_views.xml
Set automatic tracking URL based on tracking numbers for UPS provider.
> [IMP] Feature #19249 - Set automatic tracking URL based on tracking numbers for UPS provider

- bista_purchase/data/email_template.xml
- bista_purchase/models/stock_picking.py
- bista_purchase/views/stock_picking_views.xml
Added send by email functionality on shipping(picking) for delivery order only
> [IMP] Feature #19144 - added send by email functionality on shipping(picking) for delivery order only

- bista_purchase/models/purchase_order.py
- bista_sale/data/data.xml
- bista_sale/models/stock_move.py
- bista_sale/models/white_glove_type.py
- bista_sale/views/sale_order_view.xml
- bista_sale/views/stock_picking_view.xml
> [FIX] Resolving Redmine Tickets

- bista_purchase/data/email_template.xml
- bista_purchase/views/purchase_views.xml
Did some changes to the email body and restrict it to an open tracking form.
> [IMP] Feature #18175 & #19144 - Did some changes to email body and restrict to open tracking form

- bigcommerce_odoo_integration/models/res_partner.py
- bigcommerce_odoo_integration/models/sale_order.py
- bigcommerce_odoo_integration/views/sale_order.xml
- bista_bigcommerce_extend/__manifest__.py
- bista_bigcommerce_extend/models/__init__.py
- bista_bigcommerce_extend/models/sale_order.py
- bista_bigcommerce_extend/models/stock_move.py
- bista_bigcommerce_extend/views/stock_picking_view.xml
- bista_sale/__manifest__.py
- bista_sale/models/__init__.py
- bista_sale/models/sale_order.py
- bista_sale/security/security_view.xml
- bista_sale/views/sale_order_view.xml
- sale_advance_payment/__manifest__.py
- sale_advance_payment/views/sale_view.xml
Updated changes in quotation view and fixed bigcomemrce dependancy.
> [FIX]Big commerce changes

- bista_bigcommerce_extend/__manifest__.py
- bista_bigcommerce_extend/models/__init__.py
- bista_bigcommerce_extend/models/account_move.py
- bista_bigcommerce_extend/models/big_commerce_config.py
- bista_bigcommerce_extend/models/product_template.py
- bista_bigcommerce_extend/models/purchase.py
- bista_bigcommerce_extend/models/sale_order.py
- bista_bigcommerce_extend/models/stock_move.py
- bista_bigcommerce_extend/models/stock_picking.py
- bista_bigcommerce_extend/views/account_move_views.xml
- bista_bigcommerce_extend/views/purchase_views.xml
- bista_bigcommerce_extend/views/sale_order_view.xml
- bista_bigcommerce_extend/views/stock_picking_view.xml
Added product format at sales line, multi shipment, purchase order, invoice, and transfer level
> [IMP] Feature #19149 - Added product format at sales line, multi shipment, purchase order, invoice, and transfer level

- bista_bigcommerce_extend/views/stock_picking_view.xml
> [FIX] Changed sequence of Demand

- bista_customer_credit_limit_nc/models/res_partner.py
- bista_customer_credit_limit_nc/models/sale.py
solved the issue of wrong calculation of credit limit.
> [IMP] Feature #17868 - solved the issue of wrong calculation of credit limit

- bista_purchase/report/account_move.xml
- bista_purchase/report/purchase_order.xml
- bista_purchase/report/stock_picking.xml
* Bista-Purchase
------------------------
1 . Added PaparFormat For the Inventory,Purchase and Account Pdf.
> [IMP] Added paperformat for the Purchase,Inventory and Account

- bigcommerce_odoo_integration/models/res_partner.py
- bigcommerce_odoo_integration/models/sale_order.py
- bigcommerce_odoo_integration/views/res_partner.xml
- bista_avatax_exemption/models/__init__.py
- bista_avatax_exemption/models/res_partner.py
- bista_bigcommerce_extend/__init__.py
- bista_bigcommerce_extend/__manifest__.py
- bista_bigcommerce_extend/models/__init__.py
- bista_bigcommerce_extend/models/res_partner.py
- bista_bigcommerce_extend/models/sale_order.py
- bista_bigcommerce_extend/security/ir.model.access.csv
- bista_bigcommerce_extend/wizard/__init__.py
- bista_bigcommerce_extend/wizard/update_partner_view.xml
- bista_bigcommerce_extend/wizard/update_partner_wizard.py
[FIX]Fixed the tax exemption issue and fixed wrong cover price in bc order issue.
> Fixed bigcommerce bug for tax exemption and cover price in line.

- bista_sale/models/sale_order.py
- bista_stock_remarks/models/purchase_order.py
Solved issue of Return generated from Internal transfer[INT] not shown in PO level
> [IMP] Bug #19350 - Solved issue of Return generated from Internal transfer[INT] not shown in PO level

- bista_purchase/report/stock_picking.xml
- purchase_pricelist/models/product_supplierinfo.py
> issue of recursion depth issue

- bista_purchase/models/account_move.py
- bista_purchase/models/purchase_order.py
- bista_purchase/views/account_move_views.xml
Added BP price & quote price in invoice & bill level, changed label price to BP price in PO
> [IMP] Enhancements #19400 - added BP price & quote price in invoice & bill level, changed label price to BP price in PO

- purchase_pricelist/models/product_supplierinfo.py
[FIX] - Bug #18939 - issue of recursion depth issue
> [FIX] - Bug #18939 - issue of recursion depth issue

- bista_purchase/data/email_template.xml
- bista_purchase/models/purchase_order.py
- bista_purchase/models/stock_picking.py
- bista_purchase/report/account_move.xml
- bista_purchase/report/purchase.xml
- bista_purchase/report/purchase_backorder_view.xml
- bista_purchase/report/purchase_order.xml
- bista_purchase/report/purchase_quotation.xml
- bista_purchase/report/report_templates.xml
- bista_purchase/report/stock_picking.xml
- bista_sale/report/sale.xml
- bista_sale_multi_ship/report/shipment_report_view.xml
> [FIX] Fixing redmine tickets

- bista_purchase/models/purchase_order.py
update source code for calculation of process time and lead time.
> [IMP] Feature #18072 - update source code for calculation of process time and lead time

- bista_purchase/models/purchase_order.py
- bista_purchase/views/purchase_views.xml
solved issue of the related field should be read-only at PO
> [IMP] Bug #19354 - solved issue of related field should be readonly at PO

- bista_contact/views/res_partner_views.xml
- bista_crm/models/crm_lead.py
- bista_crm/views/crm_lead_views.xml
- bista_sale/models/sale_order.py
solved issue of refer by & refer org not pulling from lead to sale and from contact to lead.
> [IMP] CR #19333 - solved issue of refer by & refer org not pulling from lead to sale and from contact to lead

- bista_purchase/models/purchase_tracking.py
- bista_purchase/models/stock_picking.py
- bista_purchase/report/purchase_order.xml
- bista_purchase/report/purchase_quotation.xml
- bista_purchase/views/purchase_tracking_views.xml
- bista_purchase/views/purchase_views.xml
changed confirm shipment button label and updated status shipped when validate dropship
> [IMP] CR #19485 - changed confirm shipment button label and update status shipped when validate dropship

- bista_purchase/models/purchase_order.py
- bista_purchase/views/purchase_views.xml
Solved the issue of short close line visible in BO history.
> [IMP] Feature #18073 - solved the issue of short close line visible in BO history

- bista_purchase/report/account_move.xml
Added UOM with qty and quote price of invoice line
> [IMP] CR #19551 - Added UOM with qty and quote price of invoice line

- bista_purchase/data/email_template.xml
- bista_purchase/models/res_partner.py
- bista_purchase/views/purchase_tracking_views.xml
- bista_sale_multi_ship/models/delivery_ups.py
- bista_sale_multi_ship/models/res_partner.py
Solved the issue of traceback when editing vendor name
> [FIX] Solved issue of traceback when edit vendor name

- bista_purchase/models/account_move.py
Solved issue of subtotal decimal value in invoice.
> [IMP] CR #19659 - solved issue of subtotal decimal value in invoice

- bista_sale_multi_ship/models/delivery_ups.py
- bista_sale_multi_ship/models/sale.py
- bista_sale_multi_ship/views/sale_order_view.xml
Added vendor shipping cost for dropship sale order line.
> [IMP] Feature #19644 - added vendor shipping cost for dropship sale order line

- bista_bigcommerce_extend/report/report_invoice.xml
- bista_purchase/report/account_move.xml
Fixed invoice PDF report and invoice preview page.
> [IMP] Bug #19703 - Fixed invoice PDF report and invoice preview page

- bista_sale/models/sale_order.py
Solved issue of negative saving amount
> [IMP] CR #19659 - Solved issue of negative saving amount

- bista_purchase/data/email_template.xml
Removed ISBN and format column and added those values in the description column.
> [IMP] Bug #19707 - Removed ISBN and format column and added those values in description column

- bista_purchase/data/email_template.xml
- bista_purchase/models/purchase_order.py
Updating PO email templates like removing subtotal, and taxes, solved spacing issues.
> [IMP] Bug #19707 - Updating PO email templates like removed subtotal, taxes, solved spacing issue

- bista_purchase/data/email_template.xml
removed confirm button from the footer when sending the PO email
> [IMP] Bug #19707 - removed confirm button from footer when sending PO email

- bista_purchase/models/account_move.py
solved traceback when creating invoice from sale order
> [FIX] solved traceback when creating invoice from sale order

- bista_orders_report/models/purchase_order_line.py
- bista_purchase/data/po_status_line_data.xml
- bista_purchase/models/purchase_order.py
- bista_purchase/views/purchase_views.xml
updated PO Line status as per change requested to bookpal team
> [IMP] CR #19626 - updated PO Line status as per change requested to bookpal team

- bista_sale/models/sale_order.py
solved traceback adding sale line without customer
> [FIX] Bug #19811 - solved traceback adding sale line without customer

- bista_sales_approval/models/sale_order.py
solved issue of pay button hidden when refresh page on payment option
> [FIX] Feature #19701 - solved issue of pay button hidden when refresh page on payment option

- bista_purchase/views/purchase_views.xml
display send email button on every state of tracking PO
> [IMP] CR #19485 - display send email button on every state of tracking PO

- purchase_pricelist/models/purchase_order.py
solved traceback error when adding Lincoln product on PO.
> [FIX] Bug #19776 - solved traceback error when adding Lincoln product on PO

- bigcommerce_odoo_integration/models/sale_order.py
- bigcommerce_odoo_integration/wizard/bigcommerce_import_operation.py
- bigcommerce_odoo_integration/wizard/bigcommerce_import_operation.xml
- bista_bigcommerce_extend/models/sale_order.py
Pulled the customer's comments on notes instead of terms and conditions also added import order using bc order Id and manually run cron to import order.
> [IMP]Bug #19960

- bista_purchase/data/email_template.xml
- bista_purchase/models/purchase_order.py
- bista_purchase/report/purchase_quotation.xml
- bista_purchase/views/purchase_views.xml
- bista_sale_multi_ship/views/sale_order_view.xml
- bista_sales_approval/models/sale_order.py
added the company logo on the PO email
> [IMP] Feature #19709 - added company logo on PO email

- bista_orders_report/views/purchase_order_line_view.xml
- bista_purchase/views/purchase_views.xml
- purchase_pricelist/models/purchase_order.py
make order reference with a link to open PO directly from Purchase Order Status Report.
> [IMP] Feature #19716 - make order reference with link to open PO directly from Purchase Order Status Report

- bista_purchase/views/stock_picking_views.xml
remove the purchase tracking field edit option from the transfer form view.
> [IMP] Bug #19522 - remove purchase tracking field edit option from transfer form view

- bista_check_printing/static/src/scss/report_check.scss
- bista_purchase/report/account_move.xml
fixed the issue of the wrong Client PO Number on the Invoice PDF.
> [FIX] Bug #19703 - fixed the issue of wrong Client PO Number on Invoice PDF

- bista_purchase/report/purchase_quotation.xml
- bista_sale/models/sale_order.py
Date only visible after approving PO and changed label AM Owner to Ops Owner
> [IMP] CR #19920 - Date only visible after approve PO and changed label AM Owner to Ops Owner

- bista_sale/report/sale.xml
Updated sale's Pro-Forma Invoice PDF.
> [IMP] Bug #20086 - Updated sale's Pro-Forma Invoice PDF

- bista_sale/views/sale_order_view.xml
[IMP]Feature #19927 - improved the domain of billing and shipping address of sale orders.
> [IMP]Feature #19927

- bista_sale/report/sale.xml
- bista_sale/views/sale_order_view.xml
updated label pro-forma invoice to invoice in the print menu and PDF.
> [IMP] Bug #20086 - updated label pro-forma invoice to invoice in print menu and PDF

- bista_sale/data/email_template_data.xml
- bista_sale/models/sale_order.py
- bista_sale/report/sale.xml
- bista_sale/views/sale_order_view.xml
set proper invoice & proforma on email send and also visible button based on custom sale status.
> [IMP] Bug #20086 - set proper invoice & proforma on email send and also visible button based on custom sale status

- bista_sale/report/sale.xml
added paper format and remove blank spaces from PDF.
> [IMP] Bug #20086 - added paperformat and remove blank space from PDF

- bista_bigcommerce_extend/models/__init__.py
- bista_bigcommerce_extend/models/product.py
- bista_bigcommerce_extend/models/product_template.py
added default avatax category on products and product templates.
> [IMP] Enhancements #20137 - added default avatax category on products and product templates

- bista_sale/report/sale.xml
> [FIX] Bug #20086 - Fixed blank page issue

- bista_sale/models/sale_order.py
- bista_sale_multi_ship/data/res_config_data.xml
- bista_sale_multi_ship/models/sale.py
- bista_sale_multi_ship/models/sale_multi_ship.py
- bista_sale_multi_ship/models/stock.py
- bista_sale_multi_ship/views/sale_order_view.xml
- bista_sales_approval/models/sale_order.py
[ADD]Feature #18620 - Added new functionality to select the shipping method in shipment plan.
> [ADD]Feature #18620 

- bista_purchase/data/email_template.xml
product details should not visible on no backorders picking send by email template.
> [IMP] product details should not visible on no backorders picking's send by email template

- bista_purchase/models/purchase_order.py
Fixed traceback on opening some purchase orders.
> [FIX] Bug #20235 - Fixed traceback on opening some purchase orders

- bista_sales_approval/models/sale_order.py
the sales team is now able to edit custom fields on order booked status.
> [IMP] Enhancements #20211 - sales team now able to edit custom fields on order booked status

- bista_sale/views/sale_order_view.xml
Fixed issue of need by date changed after save.
> [FIX] Bug #20213 - Fixed issue of need by date changed after save

- bista_check_printing/static/src/scss/report_check.scss
aligned amount word part and amount in check print.
> [IMP] Enhancements #19863 - aligned amount word part and amount in check print

- bista_sale/models/res_partner.py
- bista_sale/models/sale_order.py
- bista_sale/security/ir.model.access.csv
All users are now able to update the Available Payments field value.
> [IMP] Bug #20322 - All user now able to update Available Payments field value

- bista_sale_multi_ship/models/sale.py
- bista_sale_multi_ship/report/report_register.xml
- bista_sale_multi_ship/report/shipment_report_view.xml
updated validation message and removed blank space from multi-ship PDF.
> [IMP] Bug #18252 - updated validation message and removed blank space from multi ship PDF

- purchase_pricelist/models/account_move.py
- purchase_pricelist/models/product_pricelist.py
- purchase_pricelist/models/product_supplierinfo.py
- purchase_pricelist/models/sale_order.py
- purchase_pricelist/views/sale_order_views.xml
Update product cost based on vendor pricelist and also from the stock valuation.
> [IMP] Feature #19638 - Update product cost based on vendor pricelist and also from stock valuation

- bista_sale/models/sale_order.py
solved issue of delivery qty decreasing when creating a return of pick/pack transfers.
> [FIX] Bug #20487 - solved issue of delivery qty decreasing when creating return of pick/pack transfers

- purchase_pricelist/models/product_pricelist.py
- purchase_pricelist/models/sale_order.py
added default discount policy as display discount and price.
> [FIX] Bug #20543 - added default discount policy as display discount and price.

- bista_avatax_exemption/models/account_move.py
- bista_bigcommerce_extend/models/account_move.py
Fixed the traceback issue when validate invoice line without product.
> [FIX]Fixed the traceback issue when validate invoice line

- bista_crm/__manifest__.py
- bista_crm/models/crm_lead.py
- bista_crm/views/crm_lead_views.xml
added bigcommerce customer ID & tax exempt code on CRM.
> [IMP] Feature #19438 - added bigcommerce customer ID & tax exempt code on CRM

- bista_sale/report/report_header_footer_views.xml
- bista_sale/report/sale.xml
- bista_stock_remarks/report/sale_report_template.xml
updated font size, and done some changes to product details.
> [IMP] Enhancements #20672 - updated font size, done some changes on product details

- bista_bigcommerce_extend/views/sale_order_view.xml
Hide update order BC to Odoo & update order Odoo to BC buttons after approving orders.
> [IMP] Hide update order BC to Odoo & update order Odoo to BC buttons after approve order

- bista_sale/report/report_header_footer_views.xml
- bista_sale/report/sale.xml
- bista_stock_remarks/report/sale_report_template.xml
added font family and did changes on total
> [IMP] Enhancements #20672 - added font family and did changes on total

- bista_bigcommerce_extend/models/account_move.py
- bista_bigcommerce_extend/models/sale_order.py
- bista_bigcommerce_extend/wizard/__init__.py
- bista_bigcommerce_extend/wizard/sale_make_invoice_advance.py
- bista_customer_credit_limit_nc/views/account_invoice_view.xml
- bista_purchase/models/purchase_order.py
- bista_purchase/models/purchase_tracking.py
- bista_purchase/views/purchase_tracking_views.xml
- bista_purchase/views/purchase_views.xml
set fiscal position false if big commerce order and down payment invoices also update PO tracking email sent to the customer.
> [IMP] Bug #20945 - set fiscal position false if big commerce order and down payment invoices also update PO tracking email send to customer

- bista_bigcommerce_extend/models/sale_order.py
solved the error when trying to create the final invoice.
> [FIX] Bug #20979 - solved error when try to create final invoice

- bista_sale/views/sale_templates.xml
changes on the customer payment popup.
> [IMP] Bug #21065 - changes on customer payment popup

- bista_sale/views/sale_templates.xml
hide the saved payment method label if not exist.
> [IMP] Bug #21065 - hide saved payment method label if not exist

- bista_sale/views/sale_templates.xml
update currency name before amount.
> [IMP] Enhancements #21065 - update currency name before amount

- bista_customer_credit_limit_nc/views/account_invoice_view.xml
updated invoice validation confirm message.
> [IMP] Bug #21120 - updated invoice validation confirm message

- bista_purchase/models/stock_picking.py
Sent an email to the customer on the dropship transfer
> [FIX] Bug #21094 - Sent email to customer on dropship transfer

- bista_purchase/models/purchase_order.py
- bista_sale_multi_ship/models/stock.py
solved traceback and merge purchase order line if the vendor has delivery time.
> [IMP] Bug #19717 - solved traceback and merge purchase order line if vendor has delivery time

- bista_sale/__manifest__.py
- bista_sale/models/sale_order.py
- bista_sale/models/seller_report.py
- bista_sale/security/ir.model.access.csv
- bista_sale/views/sale_order_view.xml
- bista_sale/views/seller_report_views.xml
- bista_sale/wizard/__init__.py
- bista_sale/wizard/best_seller_repor_wiz.py
- bista_sale/wizard/best_seller_report_views.xml
- bista_sale/wizard/update_seller_report.py
- bista_sale/wizard/update_seller_report_views.xml
- bista_sales_approval/models/sale_order.py
- web_tree_many2one_clickable/static/src/js/web_tree_many2one_clickable.js
best seller report changes and improvement
> [IMP] Enhancements #21340 - best seller report changes and improvement

- bista_sale/models/sale_order.py
- bista_sale/report/sale.xml
Changed button text 'Proceed to Checkout' to 'Sign & Pay' and redirect to the customer preview.
> [IMP] Enhancements #20672 - Changed button text 'Proceed to Checkout' to 'Sign & Pay' and redirect to the customer preview

- bista_sale/models/product.py
- bista_sale/models/sale_order.py
- bista_sale/models/seller_report.py
- bista_sale/views/seller_report_views.xml
- bista_sale/wizard/update_seller_report.py
- ks_dashboard_ninja/models/ks_odoo_base.py
changes on best seller reports and solve traceback.
> [IMP] Enhancements #21340 - changes on best seller report and solve traceback

- bista_sale/models/customization_type.py
- bista_sale/wizard/update_seller_report.py
updated fulfilment project field on best seller report.
> [IMP] Enhancements #21340 - updated fulfilment project field on best seller report

- bista_sale/models/sale_order.py
- bista_sale/report/so_delivery_report.xml
- bista_sale/views/sale_order_view.xml
- bista_sale/views/seller_report_views.xml
update on-time status, need-by-date label, and calculate need-by date.
> [IMP] Support #21057 - update on time status, need by date label, calculate need by date

- bista_sale/models/sale_order.py
- bista_sale/report/so_delivery_report.xml
- bista_sale/views/sale_order_view.xml
make read-only compute field and added order status on the group by the filter.
> [IMP] Support #21057 - make readonly compute field and added order status on group by filter

- bista_crm/__manifest__.py
- bista_crm/models/crm_lead.py
set proper quote sent or sale order count on the opportunity.
> [IMP] Enhancements #21582 - set proper quote sent or sale order count on opportunity
